server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_routh #payment_routh   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://SPRINGCLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂在匹配的请求头上加上一对请求头，名称为X-Request-Id为1024
          predicates:
            - Path=/payment/get/**     #断言，路径相匹配的进行路由
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://SPRINGCLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**
            #- After=2022-08-04T14:14:18.181+08:00[Asia/Shanghai]
            #- Before=2022-08-04T11:14:18.181+08:00[Asia/Shanghai]
            #- Between=2022-08-04T14:14:18.181+08:00[Asia/Shanghai],2022-08-04T15:14:18.181+08:00[Asia/Shanghai]
            #- Cookie=username,dadadefeima
            #- Header=X-Request-Id,\d+ #请求头要有X-Request-Id属性并且值为正数的正则表达式
            #- Host=**.dadadefeima.com
            #- Method=Get
            #- Query=username,\d+
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka/